name: Terragrunt Run All
description: Terragrunt run-all
inputs:
  folder:
    description: The target folder
    required: true
  iam-role:
    description: The iam role to assume
    required: true
  bin-name:
    description: The name of the executable
    required: false
    default: terragrunt
  bin-path:
    description: The bin location
    required: false
    default: /usr/local/bin
  run-all-action:
    description: The terragrunt command args
    required: true
  additional-options-args:
    description: Additional terragrunt option args
    required: false

runs:
  using: composite
  steps:
        
    - name: Terrgrunt Apply
      shell: bash
      env:
        TERRAGRUNT_IAM_ROLE: ${{ inputs.iam-role }}
      run: |
        ${{ inputs.bin-path }}/${{ inputs.bin-name }} run-all ${{ inputs.run-all-action }} --terragrunt-non-interactive --terragrunt-working-dir ${{ inputs.folder }} ${{ inputs.additional-options-args }}