name: Terragrunt Setup
description: Checks terraform complicance with aws
inputs:
  terragrunt-version:
    description: The terragrunt version to use
    required: false
    default: 'v0.31.1'
  bin-name:
    description: The name of the executable
    required: false
    default: terragrunt
  bin-dir:
    description: The bin location
    required: false
    default: /usr/local/bin
  format-ext:
    description: The type of archive
    required: false
    default: linux_amd64
runs:
  using: composite
  steps:
        
    - name: Terrgrunt Setup
      shell: bash
      env:
        TERRAGRUNT_VERSION: ${{ inputs.terragrunt-version }}
        DOWNLOAD_FORMAT_EXT: ${{ inputs.format-ext }}
      run: |
        export DOWNLOAD_URL="https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT_VERSION}/terragrunt_${DOWNLOAD_FORMAT_EXT}"
        printf "Downloading '%s' ...\n" "${DOWNLOAD_URL}"
        curl -f -Lo ${{ inputs.bin-name }} "${DOWNLOAD_URL}"
        chmod +x ${{ inputs.bin-name }}
        mv ${{ inputs.bin-name }} ${{ inputs.bin-path }}/${{ inputs.bin-name }}