name: Terragrunt Wrapper
description: Run Terragrunt with pre-configured settings
inputs:
  terragrunt_stack_path:
    description: The path to your Terragrunt stack, which contains multiple stages to run
    required: true
    default: ""
  pull_request_number:
    description: The number of the pull request to leave comments on
    required: true
    default: ""
  iam_role_to_assume:
    description: The AWS IAM role to assume when running Terragrunt
    required: false
    default: ""
runs:
  using: docker
  image: "docker://harbor.parker.gg/library/terragrunt-wrapper:v1"
  env:
    GITHUB_PR_NUMBER: ${{ inputs.pull_request_number }}
    TERRAGRUNT_STACK_PATH: ${{ inputs.terragrunt_stack_path }}
    IAM_ROLE_TO_ASSUME: ${{ inputs.iam_role_to_assume }}
