name: AWS Terraform Compliance
description: Checks terraform complicance with aws
inputs:
  target-folder:
    description: The target folder
    required: true
  subfolders:
    description: A space delimited list of sub-folders with terragrunt.hcl files
    required: true
  iam-role:
    description: The iam role to assume
    required: true
runs:
  using: composite
  steps:
    - name: List Compliance folder
      shell: bash
      run: |
        ls -la

    - name: Terraform Compliance setup
      shell: bash
      working-directory: ${{ inputs.target-folder }}
      env:
        SUBFOLDERS: ${{ inputs.subfolders }}
        TERRAGRUNT_IAM_ROLE: ${{ inputs.iam-role }}
      run: |
        for i in $SUBFOLDERS
        do
          cd $i/
          terragrunt plan -lock=false --out plan.out
          terragrunt show -json plan.out > plan.out.json
          cd ..
        done

    - name: Terraform Compliance
      shell: bash
      working-directory: ${{ inputs.target-folder }}
      env:
        TARGET_FOLDER: ${{ inputs.target-folder }}
        SUBFOLDERS: ${{ inputs.subfolders }}
      run: |
        for i in $SUBFOLDERS
        do
          ii="${TARGET_FOLDER}/${i}"
          echo "##################################################################################################################"
          echo "TERRAFORM COMPLIANCE PATH ${ii}"
          echo "##################################################################################################################"
          cd $i/
          terraform-compliance -n -p plan.out.json -f git:https://github.com/terraform-compliance/user-friendly-features.git
          echo "##################################################################################################################"
          echo "\n"
          rm plan.out.json
          cd ..
        done