name: AWS Terraform Compliance
description: Checks terraform complicance with aws
inputs:
  token:
    description: Github api token
    required: false
  target-folder:
    description: The target folder
    required: true
  subfolders:
    description: A space delimited list of sub-folders with terragrunt.hcl files
    required: false
    default: ""
  iam-role:
    description: The iam role to assume
    required: true
  plan-file:
    description: Name of plan file
    required: false
    default: plan.out
  features:
    description: Features dir or repo
    required: false
    default: git:https://github.com/terraform-compliance/user-friendly-features.git
  options:
    description: Optional parameters (https://terraform-compliance.com/pages/usage/)
    required: false
    default: |
      -n
runs:
  using: docker
  image: Dockerfile
  env:
    TARGET_FOLDER: ${{ inputs.target-folder }}
    SUBFOLDERS: ${{ inputs.subfolders }}
    TERRAGRUNT_IAM_ROLE: ${{ inputs.iam-role }}
    GH_PAT: ${{ inputs.token }}
    COMPLIANCE_COMMAND_OPTS: ${{ inputs.options }}
    PLAN_FILE: ${{ inputs.plan-file }}
    COMPLIANCE_FEATURES: ${{ inputs.features }}